DO $$
BEGIN
  CREATE TABLE CUSTOMER (
    CUSTOMER_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    NAME VARCHAR(250) NOT NULL,
    REGISTRATION_NUMBER VARCHAR(15) NOT NULL,
    CONSTRAINT CUSTOMER_PK PRIMARY KEY (CUSTOMER_ID)
  );

  COMMENT ON  TABLE CUSTOMER IS 'Table to store Customers';
  COMMENT ON COLUMN CUSTOMER.CUSTOMER_ID IS 'The Id in this table.';
  COMMENT ON COLUMN CUSTOMER.NAME IS 'The Name in this table.';

  CREATE TABLE CUSTOMER_ADDRESS (
    CUSTOMER_ADDRESS_ID UUID NOT NULL DEFAULT GEN_RANDOM_UUID(),
    CUSTOMER_ID UUID NOT NULL,
    ADDRESS VARCHAR(250) NOT NULL,
    NUMBER NUMERIC NOT NULL,
    CONSTRAINT CUSTOMER_ADDRESS_PK PRIMARY KEY (CUSTOMER_ADDRESS_ID),
    CONSTRAINT CUSTOMER_FK FOREIGN KEY (CUSTOMER_ID)
      REFERENCES CUSTOMER (CUSTOMER_ID)
        ON DELETE CASCADE
        ON UPDATE RESTRICT
  );

  COMMENT ON  TABLE CUSTOMER_ADDRESS IS 'Table to store Customer Addresses';
  COMMENT ON COLUMN CUSTOMER_ADDRESS.CUSTOMER_ADDRESS_ID IS 'The Id in this table.';
  COMMENT ON COLUMN CUSTOMER_ADDRESS.ADDRESS IS 'The Address in this table.';
  COMMENT ON COLUMN CUSTOMER_ADDRESS.NUMBER IS 'The Number in this table.';
  COMMENT ON COLUMN CUSTOMER_ADDRESS.CUSTOMER_ID IS 'The Customer Id in this table.';
END
$$;